.TH "VPC\-VMNIC\-GET" "8" "Mar 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc\-vmnic\-get \- get VMNIC information


.SH SYNOPSIS
.PP
\fBvpc vmnic get [flags]\fP


.SH DESCRIPTION
.PP
get VMNIC information


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for get

.PP
\fB\-n\fP, \fB\-\-num\-queues\fP[=true]
    get the number of hardware queues for a given VM NIC

.PP
\fB\-N\fP, \fB\-\-vmnic\-id\fP=""
    Specify the VM NIC ID


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=false]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=false]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH SEE ALSO
.PP
\fBvpc\-vmnic(8)\fP
