.TH "VPC\-MUX" "8" "Feb 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc\-mux \- VPC packet multiplexing configuration


.SH SYNOPSIS
.PP
\fBvpc mux [flags]\fP


.SH DESCRIPTION
.PP
VPC packet multiplexing configuration


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for mux


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=false]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=false]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH SEE ALSO
.PP
\fBvpc(8)\fP, \fBvpc\-mux\-create(8)\fP
