.TH "VPC\-LIST" "8" "Feb 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc\-list \- list counts of each VPC type


.SH SYNOPSIS
.PP
\fBvpc list [flags]\fP


.SH DESCRIPTION
.PP
The list operation of vpc(8) is used to display all VPC objects in the system
and their respective VPC IDs.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for list

.PP
\fB\-c\fP, \fB\-\-obj\-counts\fP[=false]
    list the number of objects per type

.PP
\fB\-t\fP, \fB\-\-obj\-type\fP="all"
    List objects of a given type. Valid types: ethlink, mgmt, vmnic, vpcmux, vpcnat, vpcp, vpcrtr, vpcsw

.PP
\fB\-s\fP, \fB\-\-sort\-by\fP="id"
    Change the sort order within a given type: id, name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=false]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=false]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH EXAMPLE
.PP
.RS

.nf
% vpc list
 TYPE     ID                                    UNIT NAME
 ethlink  5c4acd32\-1b8d\-11e8\-b408\-0cc47a6c7d1e  ethlink0
 vmnic    07f95a11\-6788\-2ae7\-c306\-ba95cff1db38  vmnic0
 vmnic    a774ba3a\-1f77\-11e8\-8006\-0cc47a6c7d1e  vmnic1
 vpcp     0ebf50e1\-1f79\-11e8\-8002\-0cc47a6c7d1e  vpcp1
 vpcp     ea58b648\-203b\-a707\-cd02\-7a552c8d5295  vpcp2
 vpcp     fd436f9c\-1f77\-11e8\-8002\-0cc47a6c7d1e  vpcp0
 vpcsw    da64c3f3\-095d\-91e5\-df01\-5aabcfc52468  vpcsw0

   TOTAL                    7

.fi
.RE


.SH SEE ALSO
.PP
\fBvpc(8)\fP
