.TH "VPC\-ETHLINK\-VTAG" "8" "Feb 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc\-ethlink\-vtag \- Get or set the VTag on a VPC EthLink


.SH SYNOPSIS
.PP
\fBvpc ethlink vtag [flags]\fP


.SH DESCRIPTION
.PP
Get or set the VTag on a VPC EthLink


.SH OPTIONS
.PP
\fB\-E\fP, \fB\-\-ethlink\-id\fP=""
    Specify the EthLink ID

.PP
\fB\-g\fP, \fB\-\-get\-vtag\fP[=true]
    get the VTag for a given VPC EthLink NIC

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for vtag

.PP
\fB\-s\fP, \fB\-\-set\-vtag\fP=\-1
    set the VTag for a given VPC EthLink NIC


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=false]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=false]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH SEE ALSO
.PP
\fBvpc\-ethlink(8)\fP
