.TH "VPC" "8" "Feb 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc \- vpc configures and manages VPCs


.SH SYNOPSIS
.PP
\fBvpc [flags]\fP


.SH DESCRIPTION
.PP
vpc configures and manages VPCs


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for vpc

.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=false]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=false]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH EXAMPLE
.PP
.RS

.nf
# Perform a setup for a VM NIC
$ doas vpc switch create \-\-vni=123 \-\-switch\-id=da64c3f3\-095d\-91e5\-df13\-5aabcfc52468
$ doas vpc vmnic create \-\-vmnic\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38
$ doas vpc vmnic set \-\-vmnic\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38 \-\-num\-queues=2
$ doas vpc switch port add \-\-switch\-id=da64c3f3\-095d\-91e5\-df13\-5aabcfc52468 \-\-port\-id=935cf569\-17aa\-11e8\-a53f\-507b9da3d9d0
$ doas vpc switch port connect \-\-port\-id=935cf569\-17aa\-11e8\-a53f\-507b9da3d9d0 \-\-interface\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38
$ doas vpc switch port add \-\-switch\-id=da64c3f3\-095d\-91e5\-df13\-5aabcfc52468 \-\-port\-id=ea58b648\-203b\-a707\-cdf6\-7a552c8d5295 \-\-uplink \-\-l2\-name=em0 \-\-ethlink\-id=5c4acd32\-1b8d\-11e8\-b4c7\-0cc47a6c7d1e

$ vpc vmnic get \-\-vmnic\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38
$ vpc list

# Perform a tear down of the above
$ doas vpc ethlink destroy \-\-ethlink\-id=5c4acd32\-1b8d\-11e8\-b4c7\-0cc47a6c7d1e
$ doas vpc switch port disconnect \-\-port\-id=935cf569\-17aa\-11e8\-a53f\-507b9da3d9d0 \-\-interface\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38
$ doas vpc vmnic destroy \-\-vmnic\-id=07f95a11\-6788\-2ae7\-c3ce\-ba95cff1db38
$ doas vpc switch port remove \-\-switch\-id=da64c3f3\-095d\-91e5\-df13\-5aabcfc52468 \-\-port\-id=935cf569\-17aa\-11e8\-a53f\-507b9da3d9d0
$ doas vpc switch destroy \-\-switch\-id=da64c3f3\-095d\-91e5\-df13\-5aabcfc52468
$ vpc list


.fi
.RE


.SH SEE ALSO
.PP
\fBvpc\-agent(8)\fP, \fBvpc\-db(8)\fP, \fBvpc\-doc(8)\fP, \fBvpc\-ethlink(8)\fP, \fBvpc\-hostlink(8)\fP, \fBvpc\-interface(8)\fP, \fBvpc\-list(8)\fP, \fBvpc\-shell(8)\fP, \fBvpc\-switch(8)\fP, \fBvpc\-version(8)\fP, \fBvpc\-vm(8)\fP, \fBvpc\-vmnic(8)\fP
