.TH "VPC" "8" "Mar 2018" "vpc 0.0.1" "vpc" 
.nh
.ad l


.SH NAME
.PP
vpc \- vpc configures and manages VPCs


.SH SYNOPSIS
.PP
\fBvpc [flags]\fP


.SH DESCRIPTION
.PP
vpc configures and manages VPCs


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for vpc

.PP
\fB\-F\fP, \fB\-\-log\-format\fP="auto"
    Specify the log format ("auto", "zerolog", or "human")

.PP
\fB\-l\fP, \fB\-\-log\-level\fP="INFO"
    Change the log level being sent to stdout

.PP
\fB\-\-use\-color\fP[=true]
    Use ASCII colors

.PP
\fB\-P\fP, \fB\-\-use\-pager\fP[=true]
    Use a pager to read the output (defaults to $PAGER, less(1), or more(1))

.PP
\fB\-Z\fP, \fB\-\-utc\fP[=false]
    Display times in UTC


.SH SEE ALSO
.PP
\fBvpc\-db(8)\fP, \fBvpc\-doc(8)\fP, \fBvpc\-ethlink(8)\fP, \fBvpc\-interface(8)\fP, \fBvpc\-list(8)\fP, \fBvpc\-run(8)\fP, \fBvpc\-shell(8)\fP, \fBvpc\-switch(8)\fP, \fBvpc\-version(8)\fP, \fBvpc\-vmnic(8)\fP
